### PR TITLE
feat: change sendHostname

### PR DESCRIPTION
**Pull request by jinwoo-kim-nhn**

### CODE REVIEW

**Comment by jinwoo-kim-nhn** [comment]
ok to test

**Comment by jinwoo-kim-nhn** [comment]
ok to test

**Comment by jinwoo-kim-nhn** [comment]
ok to test

**Comment by jinwoo-kim-nhn** [comment]
ok to test

**Comment by jinwoo-kim-nhn** [comment]
ok to test

**Comment by jinwoo-kim-nhn** [comment]
ok to test

**Comment by jungeun-cho** [comment]
[12/10] 이견없습니다.~ 수고하셨어용

**Pull request merged**
